// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN37uX1kBAhYuk1BYDADuJKFxePAwrIcA',
    appId: '1:635776089667:web:631aedb628884d9bf29ef6',
    messagingSenderId: '635776089667',
    projectId: 'spender-revamped',
    authDomain: 'spender-revamped.firebaseapp.com',
    storageBucket: 'spender-revamped.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbd8fXN4Fd-bP5KHje20eF91SeFdtYzw',
    appId: '1:635776089667:android:7c200d7a923e422bf29ef6',
    messagingSenderId: '635776089667',
    projectId: 'spender-revamped',
    storageBucket: 'spender-revamped.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcD8H0VOOKXnXzsgOQtsPM92O90RGur8',
    appId: '1:635776089667:ios:ec4af533d06b4987f29ef6',
    messagingSenderId: '635776089667',
    projectId: 'spender-revamped',
    storageBucket: 'spender-revamped.firebasestorage.app',
    iosBundleId: 'com.example.spender.spenderTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzcD8H0VOOKXnXzsgOQtsPM92O90RGur8',
    appId: '1:635776089667:ios:ec4af533d06b4987f29ef6',
    messagingSenderId: '635776089667',
    projectId: 'spender-revamped',
    storageBucket: 'spender-revamped.firebasestorage.app',
    iosBundleId: 'com.example.spender.spenderTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN37uX1kBAhYuk1BYDADuJKFxePAwrIcA',
    appId: '1:635776089667:web:19c642ef1825b0a5f29ef6',
    messagingSenderId: '635776089667',
    projectId: 'spender-revamped',
    authDomain: 'spender-revamped.firebaseapp.com',
    storageBucket: 'spender-revamped.firebasestorage.app',
  );
}
